
#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_SPK_GPIO_DOUT  GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK  GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK  GPIO_NUM_16

#define AUDIO_I2S_MIC_GPIO_DIN   GPIO_NUM_6
#define AUDIO_I2S_MIC_GPIO_SCK   GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_WS    GPIO_NUM_4

#define BOOT_BUTTON_GPIO          GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO     GPIO_NUM_39
#define VOLUME_DOWN_BUTTON_GPIO   GPIO_NUM_40

#define POWER_BATTERY_GPIO        GPIO_NUM_38
#define POWER_CHARGE_DETECT_PIN   GPIO_NUM_47
#define POWER_SLEEP_CTRL_PIN      GPIO_NUM_21

#define DISPLAY_SPI_DC_PIN    GPIO_NUM_8
#define DISPLAY_SPI_CS_PIN    GPIO_NUM_14
#define DISPLAY_SPI_SCLK_PIN  GPIO_NUM_9
#define DISPLAY_SPI_MOSI_PIN  GPIO_NUM_10
#define DISPLAY_SPI_RESET_PIN GPIO_NUM_18
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_13

#define DISPLAY_WIDTH    320
#define DISPLAY_HEIGHT   240
#define DISPLAY_SWAP_XY  true
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y true
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_SPI_SCLK_HZ (80 * 1000 * 1000)

#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#endif // _BOARD_CONFIG_H_
